language: node_js
node_js:
  - stable
install:
  - npm install -g @angular/cli # install ng cli
  - npm install codecov -g # install codecov uploader
  - npm install # install project dependencies
  - chmod +x .travis/skip_on_readme.sh
before_script:
  - .travis/skip_on_readme.sh || travis_terminate 1
  - npm run lintonly || travis_terminate 1 # ensure files pass linting
script:
  - npm run build:prod || travis_terminate 1 # build the app
  - npm run test:ci || travis_terminate 1 # run all tests
after_success:
  - npm run coverage # upload coverage results to Codacy
  - codecov # upload coverage results to Codecov
deploy: # on success, deploy to Firebase hosting
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN # using the token you got from firebase login:ci
  on:
    branch: master # if the build was on the master branch
