#!/bin/bash

###
# This hook will automatically release a new version tag on GitHub if the version in package.json changes
###

version=`git diff HEAD^..HEAD -- "$(git rev-parse --show-toplevel)"/package.json | grep '^\+.*version' | sed -s 's/[^0-9\.]//g'`

if [ "$version" != "" ]; then
    git tag -a "v$version" -m "`git log -1 --format=%s`"
    git push origin --tags
    echo "Created a new tag, v$version"
fi
