#!/bin/sh

###
# This hook will automatically lint files being committed to ensure code quality
###

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".ts")
TSLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/tslint --fix"

if [[ "$STAGED_FILES" == "" ]]; then
    exit 0
fi

PASS=true

printf "\nValidating TypeScript:\n"

# Check for tslint
if [[ ! -x "$TSLINT" ]]; then
    printf "\t\033[41mPlease install TSlint\033[0m (npm i --save-dev tslint)"
    exit 1
fi

for FILE in $STAGED_FILES; do
    "$TSLINT" "$FILE"

    if [[ "$?" == 0 ]]; then
        printf "\t\033[32mESLint Passed: $FILE\033[0m"
    else
        printf "\t\033[41mESLint Failed: $FILE\033[0m"
        PASS=false
    fi
done

printf "\nTypeScript validation completed!\n"

if ! $PASS; then
    printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass TSLint but do not. Please fix the TSLint errors and try again.\n"
    exit 1
else
    printf "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
