name: Build and Test Project
on: [push]
jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        os: [ ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies and Lint Project
      run: |
         npm install -g @angular/cli
         npm install
         npm run lint
      env:
        CI: true

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Test on node 10.x and ubuntu-latest
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Build and test Angular app
      run: |
        npm install -g @angular/cli
        npm install
        npm run build:prod
        npm run test:ci
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
      env:
        CI: true
